docs_dir: _build/pydocmd
pages:
- {Home: index.md}
- Documentation:
  - {tqdm.tqdm: docs/tqdm.md}
  - {tqdm.tqdm_gui: docs/tqdm_gui.md}
  - {tqdm.tqdm_notebook: docs/tqdm_notebook.md}
  - {Shortcuts: docs/shortcuts.md}
- Developer Documentation:
  - {Warnings and Exceptions: docs/warnings.md}
  - {tqdm.TMonitor: docs/TMonitor.md}
- {Release History: releases.md}
- {Contributing: contributing.md}
- {Ports to Other Languages: ports.md}
- External Links:
  - {Source Code (ENTIRE DOCUMENTATION ON ONE PAGE): 'https://github.com/tqdm/tqdm'}
  - {wiki: 'https://github.com/tqdm/tqdm/wiki'}
  - Downloads:
    - {GitHub: 'https://github.com/tqdm/tqdm/releases'}
    - {PyPI: 'https://pypi.org/project/tqdm'}
    - {Conda: 'https://anaconda.org/conda-forge/tqdm'}
  - Tests:
    - {Travis CI: 'https://travis-ci.org/tqdm/tqdm'}
    - {Coveralls: 'https://coveralls.io/github/tqdm/tqdm'}
    - {Codecov: 'https://codecov.io/gh/tqdm/tqdm'}
    - {Codacy: 'https://www.codacy.com/app/tqdm/tqdm'}
    - {Performance Benchmarks (asv): 'https://tqdm.github.io/tqdm'}
  - Citations:
    - {DOI (Zenodo): 'https://zenodo.org/badge/latestdoi/21637/tqdm/tqdm'}
    - {Metrics (Open Hub): 'https://www.openhub.net/p/tqdm'}
- {Licence: licence.md}
repo_url: https://github.com/tqdm/tqdm
site_dir: _build/site
site_name: tqdm documentation
theme: readthedocs
